refactor: Improve scaffolding
scoutredeem/scaffolding pull request #3
Opened 2024-11-28 06:14 UTC by paurakhsharma

2024-11-28 12:19 UTC, JannieT requested changes
Can you please:
- try the suggestion to avoid watching the widget tree root
- add a network service with a good body perser like we have in [Alpha Plus app](https://dev.azure.com/alphaglobal/GuestExperience/_git/GuestExperienceMobile?path=/lib/src/shared/services/network_service.dart)

2024-11-29 05:20 UTC, paurakhsharma commented on flutter/lib/src/app.dart
> +          themeMode: themeMode,
Previous approach was doing the same thing as well. We should rebuild the whole app when the theme is changed. I think the solution you suggested would do the same thing as well. But I will experiment to see if that is correct. Thank you for the suggestion.

2024-11-29 08:55 UTC, paurakhsharma commented
@JannieT PR updated.

2024-11-29 08:55 UTC, paurakhsharma commented on flutter/init.js
> +  const defaultBundleId = `co.scoutredeem`;
No the last one was incorrect, the org value should not include the package name.

2024-11-29 15:03 UTC, merged